# Generated by Django 6.0.3 on 2026-03-24 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_profile_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment / Flat'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('selfcon', 'Self-contained'), ('shortlet', 'Short Let'), ('land', 'Land')], max_length=20)),
                ('listing_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('shortlet', 'Short Let')], default='rent', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Review'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('location', models.CharField(choices=[('Lekki Phase 1', 'Lekki Phase 1'), ('Lekki Phase 2', 'Lekki Phase 2'), ('Ikoyi', 'Ikoyi'), ('Victoria Island', 'Victoria Island'), ('Surulere', 'Surulere'), ('Ikeja', 'Ikeja'), ('Ajah', 'Ajah'), ('Yaba', 'Yaba'), ('Gbagada', 'Gbagada'), ('Magodo', 'Magodo'), ('Festac', 'Festac'), ('Isale Eko', 'Isale Eko')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Annual rent or sale price in Naira')),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('toilets', models.PositiveSmallIntegerField(default=1)),
                ('size', models.PositiveIntegerField(blank=True, help_text='Size in m²', null=True)),
                ('has_water', models.BooleanField(default=False)),
                ('has_generator', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_bq', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_wardrobe', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='Main.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
